services:
 mongo: 
  image: mongo:latest
  container_name: "mongo"
  ports:
   - 27017:27017
  volumes_from:
        - data

 data:
    image: mongo:latest
    volumes:
        - /var/lib/mongo
        - ./setup:/setup
    command: "true"
    container_name: "temp"
networks:
 default:
  external:
   name: net
