services:
 react:
  container_name: "react"
  build:
   context: ./frontend/
   dockerfile: Dockerfile
  ports:
   - 3000:3000
  depends_on:
    - spring
    - mongo
 spring:
  container_name: "spring"
  build: 
   context: .
   dockerfile: Dockerfile
  ports:
   - 8081:8081
  depends_on: 
   - mongo
 
 mongo: 
  image: mongo:latest
  container_name: "mongo"
  ports:
   - 27017:27017
  volumes_from:
        - data

 data:
    image: mongo:latest
    volumes:
        - /var/lib/mongo
        - ./setup:/setup
    command: "true"
    container_name: "temp"
networks:
 default:
  external:
   name: net
