---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: Copying setup folder
      become: false
      copy:
        src: ./setup
        dest: ./
        owner: manthan
        group: manthan
        mode: 0777
    - name: Copying script file
      become: false
      copy:
        src: ./scriptfile.sh
        dest: ./
        owner: manthan
        group: manthan
        mode: 0777
    - name : Run Docker compose
      ansible.builtin.shell:
        cmd: sh scriptfile.sh

