---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: Copying setup folder
      become: true 
      copy:
        src: ./setup
        dest: ./
        
    - name: Copying script file
      become: true 
      copy:
        src: ./scriptfile.sh
        dest: ./
        
    - name: Run Docker compose
      ansible.builtin.shell:
        cmd: sh scriptfile.sh

